# Generated by Django 2.0.2 on 2018-04-09 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_auto_20180408_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='User',
            new_name='user',
        ),
    ]
